### ISSUE TITLE
possible code typo in colorblind async/await post

### ISSUE THREAD

**Issue by mwcz** [kristoff-it/kristoff.it#2]
Hey, I can't figure out where to submit a PR, as the blog post content is in a single-line JSON file, but hopefully this issue helps.  There's a missing keyword (I think, I'm a huge zig noob) in the "One final trick" section of the [What is Zig's “Colorblind” Async/Await?](https://kristoff.it/blog/zig-colorblind-async-await/) post.

Trying to run the code sample as written.

```text
./blocking.zig:18:31: error: type '@typeInfo(@typeInfo(@TypeOf(std.net.tcpConnectToAddress)).Fn.return_type.?).ErrorUnion.error_set!std.net.Stream' does not support field access
    _ = try await async socket.write("Hello World!\n");
                              ^
./blocking.zig:10:15: note: referenced here
    try await sendFrame;
              ^
/usr/lib/zig/std/start.zig:458:40: note: referenced here
            const result = root.main() catch |err| {
                                       ^
```

Adding this patch fixed it.

```diff
- var socket = net.tcpConnectToAddress(addr);
+ var socket = try net.tcpConnectToAddress(addr);
```

**Comment by kristoff-it** [comment]
took a while, but I eventually fixed it :^)
